name: 'Setup Lua'
description: 'Setup Lua'

runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get install -y gcc tar make
        wget http://www.lua.org/ftp/lua-5.4.3.tar.gz
        tar -xf lua-5.4.3.tar.gz
        cd lua-5.4.3
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-linux.tar.gz
        tar -xf premake-5.0.0-alpha16-linux.tar.gz
        rm -fr premake-5.0.0-alpha16-linux.tar.gz
        wget https://gist.githubusercontent.com/Vipul-Cariappa/2e957b77f5d6dde7c0b6d01c04beb911/raw/e65c95968cf36503f6cbc6819761a6b2220f3b69/premake5.lua
        ./premake5 gmake
        make
        sudo cp bin/lib/Debug/liblua.so /usr/lib/
        sudo cp bin/exec/interpreter/Debug/luai /usr/bin/lua
        sudo cp bin/exec/compiler/Debug/luac /usr/bin/luac
        sudo cp -r src/ /usr/include/lua5.4/
        cd ..
        rm -fr lua-5.4.3
      shell: bash
