on: [push]

jobs:
  test_lua:
    runs-on: ubuntu-latest
    name: Test Lua
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: Vipul-Cariappa/lua-action@test
      - run: lua -v
        shell: bash